# These are supported funding model platforms

# If you want to add funding options later:
# github: bjornshomelab
# patreon: your_username
# ko_fi: your_username
# custom: ["https://yourwebsite.com/donate"]
